# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Probably Won't Get to Mongolia
tagline:             The Jekyll Butler
url:                 http://probablywontgettomongolia.com
paginate:            1
baseurl:             "/"

# About/contact
author:
  name:              Thomas Lim
  url:               https://twitter.com/t8lim
  email:             txsl@outlook.com

# Custom vars
github:
  repo:              https://github.com/txsl/probablywontgettomongolia.com
